### Frontend (dev server, proxied to backend)
GET http://localhost:3001


### Get auth token
# Note: try using https://jwt.io/ to decode the token from the response

POST http://localhost:3001/auth/register
content-type: application/json

{
    "username":"John Doe",
    "roles":"[\"admin\"]"
}

### Validate auth token (requires token from previous example)
# Note: you will need an up-to-date token from the previous step

GET http://localhost:3001/api/protected
accept: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG4gRG9lIiwicm9sZXMiOiJbXCJhZG1pblwiXSIsImlhdCI6MTY0Nzg5ODU4MywiZXhwIjoxNjQ3OTAwMzgzfQ.M151tM39ummyhm1m6GYZHZfuG8-t32DA1evjX2kV5AE

###
GET http://localhost:3001/auth/login

### 
GET http://localhost:3001/auth/logout
