import React, { useState } from "react";
import { useAuth0 } from "@auth0/auth0-react";
import { Button, Box, Paper } from "@mui/material";
import "./styles.css";
import { auth } from '../../../config'




// Define a React component called SplashPage
const SplashPage = () => {
  // Use the useAuth0 hook from the Auth0 React library to get the loginWithRedirect function
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');

  const { user, isAuthenticated, isLoading, error, createUser, getAccessTokenSilently } = useAuth0();
  

  const handleSubmit = async (event) => {
    event.preventDefault();
    const accessToken =  await getAccessTokenSilently();
    const response = await  fetch(
      `${auth.REACT_APP_AUTH0_DOMAIN}/api/v2/users`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${accessToken}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          email: username,
          password: password,
          connection: 'Username-Password-Authentication'
        })
      }
    );
    const data = await response.json();
    console.log(data);
  };

  if (isLoading) {
    return <div>Loading ...</div>;
  }

  if (error) {
    return <div>{error.message}</div>;
  }

  // Return a JSX element that displays a login form with a background image and text
  return (
    
    
    <div style={{margin: 0, blockSize: '873px', boxSizing: 'content-box', fontFamily: 'National2, National2Condensed, monospace, sans-serif', fontSize: '20px', inlineSize: '1900px'}} >
    <div style={{backgroundColor: 'rgb(228, 0, 43)', blockSize: '59px', borderBlockEndColor: 'rgb(255, 255, 255)', borderBlockStartColor: 'rgb(255, 255, 255)', borderBottomColor: 'rgb(255, 255, 255)', borderInlineEndColor: 'rgb(255, 255, 255)', borderInlineStartColor: 'rgb(255, 255, 255)', borderLeftColor: 'rgb(255, 255, 255)', borderRightColor: 'rgb(255, 255, 255)', borderTopColor: 'rgb(255, 255, 255)', bottom: '0px', boxSizing: 'content-box', caretColor: 'rgb(255, 255, 255)', color: 'rgb(255, 255, 255)', columnRuleColor: 'rgb(255, 255, 255)', fontFamily: 'National2Condensed', fontSize: '20px', inlineSize: '1900px', insetBlockEnd: '0px', insetBlockStart: '0px', insetInlineEnd: '0px', insetInlineStart: '0px', left: '0px', marginLeft: 0, marginRight: 0, outlineColor: 'rgb(255, 255, 255)', paddingBlockEnd: '12px', paddingBlockStart: '12px', paddingBottom: '12px', paddingTop: '12px', position: 'relative', right: '0px', textAlign: 'center', textDecoration: 'none solid rgb(255, 255, 255)', textDecorationColor: 'rgb(255, 255, 255)', textEmphasisColor: 'rgb(255, 255, 255)', top: '0px', WebkitTextFillColor: 'rgb(255, 255, 255)', WebkitTextStrokeColor: 'rgb(255, 255, 255)'}} className = {"topBar"} >
        <a style={{blockSize: '59px', borderBlockEndColor: 'rgb(255, 255, 255)', borderBlockStartColor: 'rgb(255, 255, 255)', borderBottomColor: 'rgb(255, 255, 255)', borderInlineEndColor: 'rgb(255, 255, 255)', borderInlineStartColor: 'rgb(255, 255, 255)', borderLeftColor: 'rgb(255, 255, 255)', borderRightColor: 'rgb(255, 255, 255)', borderTopColor: 'rgb(255, 255, 255)', boxSizing: 'content-box', caretColor: 'rgb(255, 255, 255)', color: 'rgb(255, 255, 255)', columnRuleColor: 'rgb(255, 255, 255)', cursor: 'pointer', display: 'block', fontFamily: 'National2Condensed', fontSize: '20px', inlineSize: '1900px', letterSpacing: '2px', lineHeight: '56px', marginLeft: 0, marginRight: 0, outlineColor: 'rgb(255, 255, 255)', textAlign: 'center', textDecoration: 'none', textDecorationColor: 'rgb(255, 255, 255)', textEmphasisColor: 'rgb(255, 255, 255)', WebkitTextFillColor: 'rgb(255, 255, 255)', WebkitTextStrokeColor: 'rgb(255, 255, 255)'}} className = {"topBar__logo"} >
            <div style={{backgroundColor: 'rgb(255, 255, 255)', backgroundImage: 'url(https://teamkfc.yum.com/images/images/Colonel.png)', backgroundRepeat: 'no-repeat', backgroundSize: 'cover', blockSize: '56px', borderBlockEndColor: 'rgb(228, 0, 43)', borderBlockEndStyle: 'solid', borderBlockEndWidth: '1px', borderBlockStartColor: 'rgb(228, 0, 43)', borderBlockStartStyle: 'solid', borderBlockStartWidth: '1px', borderBottomColor: 'rgb(228, 0, 43)', borderBottomLeftRadius: '100%', borderBottomRightRadius: '100%', borderBottomStyle: 'solid', borderBottomWidth: '1px', borderEndEndRadius: '100%', borderEndStartRadius: '100%', borderInlineEndColor: 'rgb(228, 0, 43)', borderInlineEndStyle: 'solid', borderInlineEndWidth: '1px', borderInlineStartColor: 'rgb(228, 0, 43)', borderInlineStartStyle: 'solid', borderInlineStartWidth: '1px', borderLeftColor: 'rgb(228, 0, 43)', borderLeftStyle: 'solid', borderLeftWidth: '1px', borderRightColor: 'rgb(228, 0, 43)', borderRightStyle: 'solid', borderRightWidth: '1px', borderStartEndRadius: '100%', borderStartStartRadius: '100%', borderTopColor: 'rgb(228, 0, 43)', borderTopLeftRadius: '100%', borderTopRightRadius: '100%', borderTopStyle: 'solid', borderTopWidth: '1px', boxSizing: 'content-box', caretColor: 'rgb(255, 255, 255)', color: 'rgb(255, 255, 255)', columnRuleColor: 'rgb(255, 255, 255)', cursor: 'pointer', display: 'inline-block', fontFamily: 'National2Condensed', fontSize: '20px', inlineSize: '56px', letterSpacing: '2px', lineHeight: '56px', marginLeft: 0, marginRight: 0, outlineColor: 'rgb(255, 255, 255)', textAlign: 'center', textDecoration: 'none solid rgb(255, 255, 255)', textDecorationColor: 'rgb(255, 255, 255)', textEmphasisColor: 'rgb(255, 255, 255)', verticalAlign: 'middle', WebkitTextFillColor: 'rgb(255, 255, 255)', WebkitTextStrokeColor: 'rgb(255, 255, 255)', width: '56px', height: '56px'}} className = {"topBar__image"} ></div>
            <span style={{blockSize: '56px', borderBlockEndColor: 'rgb(255, 255, 255)', borderBlockStartColor: 'rgb(255, 255, 255)', borderBottomColor: 'rgb(255, 255, 255)', borderInlineEndColor: 'rgb(255, 255, 255)', borderInlineStartColor: 'rgb(255, 255, 255)', borderLeftColor: 'rgb(255, 255, 255)', borderRightColor: 'rgb(255, 255, 255)', borderTopColor: 'rgb(255, 255, 255)', boxSizing: 'content-box', caretColor: 'rgb(255, 255, 255)', color: 'rgb(255, 255, 255)', columnRuleColor: 'rgb(255, 255, 255)', cursor: 'pointer', display: 'inline-block', fontFamily: 'National2Condensed', fontSize: '50px', fontWeight: 700, inlineSize: '169.852px', letterSpacing: '2px', lineHeight: '56px', marginInlineStart: '10px', marginLeft: '10px', marginRight: 0, outlineColor: 'rgb(255, 255, 255)', textAlign: 'center', textDecoration: 'none solid rgb(255, 255, 255)', textDecorationColor: 'rgb(255, 255, 255)', textEmphasisColor: 'rgb(255, 255, 255)', verticalAlign: 'middle', WebkitTextFillColor: 'rgb(255, 255, 255)', WebkitTextStrokeColor: 'rgb(255, 255, 255)'}} className = {"topBar__title"} >TEAMKFC</span>
        </a>
    </div>
    <div style={{blockSize: '690px', boxSizing: 'content-box', fontFamily: 'National2, National2Condensed, monospace, sans-serif', fontSize: '20px', inlineSize: '1900px', marginLeft: 0, marginRight: 0}} className = {"mainContainer"} >
        <div style={{blockSize: '690px', boxSizing: 'content-box', fontFamily: 'National2, National2Condensed, monospace, sans-serif', fontSize: '20px', inlineSize: '950px', marginBlockStart: '100px', marginInlineEnd: '475px', marginInlineStart: '475px', marginLeft: 'auto', marginRight: 'auto', marginTop: '100px', width: '950px', height: '690px'}} >
            
            <div style={{backgroundColor: 'rgb(255, 255, 255)', blockSize: '435px', borderBottomLeftRadius: '8px', borderBottomRightRadius: '8px', borderEndEndRadius: '8px', borderEndStartRadius: '8px', borderStartEndRadius: '8px', borderStartStartRadius: '8px', borderTopLeftRadius: '8px', borderTopRightRadius: '8px', boxShadow: 'rgba(0, 0, 0, 0.1) 0px 3px 10px 0px', boxSizing: 'content-box', fontFamily: 'National2, National2Condensed, monospace, sans-serif', fontSize: '20px', inlineSize: '950px', marginLeft: 0, marginRight: 0}} className = {"center"} >
                <div style={{blockSize: '433px', borderBlockEndColor: 'rgba(0, 0, 0, 0)', borderBlockEndStyle: 'solid', borderBlockEndWidth: '1px', borderBlockStartColor: 'rgba(242, 242, 242, 0.95)', borderBlockStartStyle: 'solid', borderBlockStartWidth: '1px', borderBottomColor: 'rgba(0, 0, 0, 0)', borderBottomStyle: 'solid', borderBottomWidth: '1px', borderInlineEndColor: 'rgba(0, 0, 0, 0)', borderInlineEndStyle: 'solid', borderInlineEndWidth: '1px', borderInlineStartColor: 'rgba(242, 242, 242, 0.95)', borderInlineStartStyle: 'solid', borderInlineStartWidth: '1px', borderLeftColor: 'rgba(242, 242, 242, 0.95)', borderLeftStyle: 'solid', borderLeftWidth: '1px', borderRightColor: 'rgba(0, 0, 0, 0)', borderRightStyle: 'solid', borderRightWidth: '1px', borderTopColor: 'rgba(242, 242, 242, 0.95)', borderTopStyle: 'solid', borderTopWidth: '1px', boxSizing: 'content-box', display: 'table-cell', fontFamily: 'National2, National2Condensed, monospace, sans-serif', fontSize: '20px', inlineSize: '530px', marginLeft: 0, marginRight: 0}} className = {"left"} >
                    <form style={{blockSize: '353px', boxSizing: 'content-box', fontFamily: 'National2, National2Condensed, monospace, sans-serif', fontSize: '20px', inlineSize: '344.5px', marginBlockEnd: '40px', marginBlockStart: '40px', marginBottom: '40px', marginInlineEnd: '92.75px', marginInlineStart: '92.75px', marginLeft: 'auto', marginRight: 'auto', marginTop: '40px', width: '344.5px', height: '353px'}} id = {"frm"} className = {"form"} action = {"/pkmslogin.form"} method = {"POST"} >
                        <div style={{blockSize: '26px', boxSizing: 'content-box', fontFamily: 'National2, National2Condensed, monospace, sans-serif', fontSize: '20px', fontWeight: 700, inlineSize: '344.5px', marginLeft: 0, marginRight: 0}} className = {"formLabel"} >Username</div>
                        <input style={{blockSize: '31.5px', borderBlockEndColor: 'rgb(213, 213, 214)', borderBlockEndStyle: 'solid', borderBlockStartColor: 'rgb(213, 213, 214)', borderBlockStartStyle: 'solid', borderBottomColor: 'rgb(213, 213, 214)', borderBottomStyle: 'solid', borderInlineEndColor: 'rgb(213, 213, 214)', borderInlineEndStyle: 'solid', borderInlineStartColor: 'rgb(213, 213, 214)', borderInlineStartStyle: 'solid', borderLeftColor: 'rgb(213, 213, 214)', borderLeftStyle: 'solid', borderRightColor: 'rgb(213, 213, 214)', borderRightStyle: 'solid', borderTopColor: 'rgb(213, 213, 214)', borderTopStyle: 'solid', boxSizing: 'border-box', caretColor: 'rgb(161, 161, 161)', color: 'rgb(161, 161, 161)', columnRuleColor: 'rgb(161, 161, 161)', display: 'block', fontSize: '17px', inlineSize: '344.5px', marginLeft: 0, marginRight: 0, outlineColor: 'rgb(161, 161, 161)', paddingBlockEnd: '4px', paddingBlockStart: '4px', paddingBottom: '4px', paddingInlineEnd: '4px', paddingInlineStart: '4px', paddingLeft: '4px', paddingRight: '4px', paddingTop: '4px', textDecoration: 'none solid rgb(161, 161, 161)', textDecorationColor: 'rgb(161, 161, 161)', textEmphasisColor: 'rgb(161, 161, 161)', WebkitTextFillColor: 'rgb(161, 161, 161)', WebkitTextStrokeColor: 'rgb(161, 161, 161)', width: '100%'}} className = {"formInput"} id = {"username"} type = {"text"} autoComplete = {"username"} tabIndex = {1} aria-labelledby = {"Username"} ></input>
                        <div style={{blockSize: '26px', boxSizing: 'content-box', fontFamily: 'National2, National2Condensed, monospace, sans-serif', fontSize: '20px', fontWeight: 700, inlineSize: '344.5px', marginBlockStart: '25px', marginLeft: 0, marginRight: 0, marginTop: '25px'}} className = {"formLabel"} >Password</div>
                        <input style={{blockSize: '31.5px', borderBlockEndColor: 'rgb(213, 213, 214)', borderBlockEndStyle: 'solid', borderBlockStartColor: 'rgb(213, 213, 214)', borderBlockStartStyle: 'solid', borderBottomColor: 'rgb(213, 213, 214)', borderBottomStyle: 'solid', borderInlineEndColor: 'rgb(213, 213, 214)', borderInlineEndStyle: 'solid', borderInlineStartColor: 'rgb(213, 213, 214)', borderInlineStartStyle: 'solid', borderLeftColor: 'rgb(213, 213, 214)', borderLeftStyle: 'solid', borderRightColor: 'rgb(213, 213, 214)', borderRightStyle: 'solid', borderTopColor: 'rgb(213, 213, 214)', borderTopStyle: 'solid', boxSizing: 'border-box', caretColor: 'rgb(161, 161, 161)', color: 'rgb(161, 161, 161)', columnRuleColor: 'rgb(161, 161, 161)', display: 'block', fontSize: '17px', inlineSize: '344.5px', marginLeft: 0, marginRight: 0, outlineColor: 'rgb(161, 161, 161)', paddingBlockEnd: '4px', paddingBlockStart: '4px', paddingBottom: '4px', paddingInlineEnd: '4px', paddingInlineStart: '4px', paddingLeft: '4px', paddingRight: '4px', paddingTop: '4px', textDecoration: 'none solid rgb(161, 161, 161)', textDecorationColor: 'rgb(161, 161, 161)', textEmphasisColor: 'rgb(161, 161, 161)', WebkitTextFillColor: 'rgb(161, 161, 161)', WebkitTextStrokeColor: 'rgb(161, 161, 161)', width: '100%'}} className = {"formInput"} id = {"password"} type = {"password"} autoComplete = {"current-password"} tabIndex = {2} aria-labelledby = {"Password"} ></input>
                        <input style={{appearance: 'none', backgroundColor: 'rgba(0, 0, 0, 0)', borderBlockEndColor: 'rgb(0, 0, 0)', borderBlockEndStyle: 'none', borderBlockEndWidth: '0px', borderBlockStartColor: 'rgb(0, 0, 0)', borderBlockStartStyle: 'none', borderBlockStartWidth: '0px', borderBottomColor: 'rgb(0, 0, 0)', borderBottomStyle: 'none', borderBottomWidth: '0px', borderInlineEndColor: 'rgb(0, 0, 0)', borderInlineEndStyle: 'none', borderInlineEndWidth: '0px', borderInlineStartColor: 'rgb(0, 0, 0)', borderInlineStartStyle: 'none', borderInlineStartWidth: '0px', borderLeftColor: 'rgb(0, 0, 0)', borderLeftStyle: 'none', borderLeftWidth: '0px', borderRightColor: 'rgb(0, 0, 0)', borderRightStyle: 'none', borderRightWidth: '0px', borderTopColor: 'rgb(0, 0, 0)', borderTopStyle: 'none', borderTopWidth: '0px', boxSizing: 'border-box', cursor: 'default', display: 'block', marginLeft: 0, marginRight: 0, paddingBlockEnd: '0px', paddingBlockStart: '0px', paddingBottom: '0px', paddingInlineEnd: '0px', paddingInlineStart: '0px', paddingLeft: '0px', paddingRight: '0px', paddingTop: '0px'}} type = {"hidden"} value = {"pwd"} ></input>
                        <a style={{blockSize: '18.5px', borderBlockEndColor: 'rgb(228, 0, 43)', borderBlockStartColor: 'rgb(228, 0, 43)', borderBottomColor: 'rgb(228, 0, 43)', borderInlineEndColor: 'rgb(228, 0, 43)', borderInlineStartColor: 'rgb(228, 0, 43)', borderLeftColor: 'rgb(228, 0, 43)', borderRightColor: 'rgb(228, 0, 43)', borderTopColor: 'rgb(228, 0, 43)', boxSizing: 'content-box', caretColor: 'rgb(228, 0, 43)', color: 'rgb(228, 0, 43)', columnRuleColor: 'rgb(228, 0, 43)', cursor: 'pointer', display: 'block', fontFamily: 'National2, National2Condensed, monospace, sans-serif', fontSize: '14px', inlineSize: '344.5px', marginBlockStart: '10px', marginLeft: 0, marginRight: 0, marginTop: '10px', outlineColor: 'rgb(228, 0, 43)', textDecoration: 'none', textDecorationColor: 'rgb(228, 0, 43)', textEmphasisColor: 'rgb(228, 0, 43)', WebkitTextFillColor: 'rgb(228, 0, 43)', WebkitTextStrokeColor: 'rgb(228, 0, 43)'}} id = {"forgotPassword"} className = {"forgotPassword"} href = {"https://password.yum.com/self-service/password"} >Forgot your Username/Password?
                        </a>
                        <button style={{backgroundColor: 'rgb(228, 0, 43)', blockSize: '42.5px', borderBlockEndColor: 'rgb(228, 0, 43)', borderBlockEndStyle: 'solid', borderBlockStartColor: 'rgb(228, 0, 43)', borderBlockStartStyle: 'solid', borderBottomColor: 'rgb(228, 0, 43)', borderBottomLeftRadius: '3px', borderBottomRightRadius: '3px', borderBottomStyle: 'solid', borderEndEndRadius: '3px', borderEndStartRadius: '3px', borderInlineEndColor: 'rgb(228, 0, 43)', borderInlineEndStyle: 'solid', borderInlineStartColor: 'rgb(228, 0, 43)', borderInlineStartStyle: 'solid', borderLeftColor: 'rgb(228, 0, 43)', borderLeftStyle: 'solid', borderRightColor: 'rgb(228, 0, 43)', borderRightStyle: 'solid', borderStartEndRadius: '3px', borderStartStartRadius: '3px', borderTopColor: 'rgb(228, 0, 43)', borderTopLeftRadius: '3px', borderTopRightRadius: '3px', borderTopStyle: 'solid', boxSizing: 'border-box', caretColor: 'rgb(255, 255, 255)', color: 'rgb(255, 255, 255)', columnRuleColor: 'rgb(255, 255, 255)', fontSize: '16px', fontWeight: 700, inlineSize: '344.5px', marginBlockStart: '40px', marginLeft: 0, marginRight: 0, marginTop: '40px', outlineColor: 'rgb(255, 255, 255)', paddingBlockEnd: '10px', paddingBlockStart: '10px', paddingBottom: '10px', paddingInlineEnd: '0px', paddingInlineStart: '0px', paddingLeft: '0px', paddingRight: '0px', paddingTop: '10px', textDecoration: 'none solid rgb(255, 255, 255)', textDecorationColor: 'rgb(255, 255, 255)', textEmphasisColor: 'rgb(255, 255, 255)', WebkitTextFillColor: 'rgb(255, 255, 255)', WebkitTextStrokeColor: 'rgb(255, 255, 255)', width: '100%'}} id = {"submitBtn"} type = {"submit"} onClick = {handleSubmit} >Log In</button>
                       
                    </form>
                </div>
                <div style={{blockSize: '433px', borderBlockEndColor: 'rgba(0, 0, 0, 0)', borderBlockEndStyle: 'solid', borderBlockEndWidth: '1px', borderBlockStartColor: 'rgba(242, 242, 242, 0.95)', borderBlockStartStyle: 'solid', borderBlockStartWidth: '1px', borderBottomColor: 'rgba(0, 0, 0, 0)', borderBottomStyle: 'solid', borderBottomWidth: '1px', borderInlineEndColor: 'rgba(0, 0, 0, 0)', borderInlineEndStyle: 'solid', borderInlineEndWidth: '1px', borderInlineStartColor: 'rgba(242, 242, 242, 0.95)', borderInlineStartStyle: 'solid', borderInlineStartWidth: '1px', borderLeftColor: 'rgba(242, 242, 242, 0.95)', borderLeftStyle: 'solid', borderLeftWidth: '1px', borderRightColor: 'rgba(0, 0, 0, 0)', borderRightStyle: 'solid', borderRightWidth: '1px', borderTopColor: 'rgba(242, 242, 242, 0.95)', borderTopStyle: 'solid', borderTopWidth: '1px', boxSizing: 'content-box', display: 'table-cell', fontFamily: 'National2, National2Condensed, monospace, sans-serif', fontSize: '14px', inlineSize: '416px', marginLeft: 0, marginRight: 0}} className = {"right"} >
                    <div style={{blockSize: '157px', boxSizing: 'content-box', fontFamily: 'National2, National2Condensed, monospace, sans-serif', fontSize: '14px', inlineSize: '270.398px', marginBlockEnd: '40px', marginBlockStart: '40px', marginBottom: '40px', marginInlineEnd: '72.8047px', marginInlineStart: '72.7969px', marginLeft: 'auto', marginRight: 'auto', marginTop: '40px', width: '270.398px', height: '157px'}} className = {"accessContainer"} >
                        <h3 style={{blockSize: '21.5px', boxSizing: 'content-box', fontFamily: 'National2, National2Condensed, monospace, sans-serif', fontSize: '16.38px', inlineSize: '270.398px', marginBlockEnd: '15px', marginBlockStart: '0px', marginBottom: '15px', marginLeft: 0, marginRight: 0, marginTop: '0px'}} id = {"accessText"} >Need to Access the Site?</h3>
                        <p style={{blockSize: '55.5px', borderBlockEndColor: 'rgb(181, 181, 181)', borderBlockStartColor: 'rgb(181, 181, 181)', borderBottomColor: 'rgb(181, 181, 181)', borderInlineEndColor: 'rgb(181, 181, 181)', borderInlineStartColor: 'rgb(181, 181, 181)', borderLeftColor: 'rgb(181, 181, 181)', borderRightColor: 'rgb(181, 181, 181)', borderTopColor: 'rgb(181, 181, 181)', boxSizing: 'content-box', caretColor: 'rgb(181, 181, 181)', color: 'rgb(181, 181, 181)', columnRuleColor: 'rgb(181, 181, 181)', fontFamily: 'National2, National2Condensed, monospace, sans-serif', fontSize: '14px', inlineSize: '270.398px', marginBlockEnd: '20px', marginBlockStart: '0px', marginBottom: '20px', marginLeft: 0, marginRight: 0, marginTop: '0px', outlineColor: 'rgb(181, 181, 181)', textDecoration: 'none solid rgb(181, 181, 181)', textDecorationColor: 'rgb(181, 181, 181)', textEmphasisColor: 'rgb(181, 181, 181)', WebkitTextFillColor: 'rgb(181, 181, 181)', WebkitTextStrokeColor: 'rgb(181, 181, 181)'}} className = {"accessMSG"} id = {"accessmsgID"} >
                            Complete the Request for Access
                            process. A request will be submitted to your organization's Security Approver for
                            approval.
                        </p>
                        <a style={{blockSize: '21px', borderBlockEndColor: 'rgb(228, 0, 43)', borderBlockEndStyle: 'solid', borderBlockEndWidth: '2px', borderBlockStartColor: 'rgb(228, 0, 43)', borderBlockStartStyle: 'solid', borderBlockStartWidth: '2px', borderBottomColor: 'rgb(228, 0, 43)', borderBottomLeftRadius: '3px', borderBottomRightRadius: '3px', borderBottomStyle: 'solid', borderBottomWidth: '2px', borderEndEndRadius: '3px', borderEndStartRadius: '3px', borderInlineEndColor: 'rgb(228, 0, 43)', borderInlineEndStyle: 'solid', borderInlineEndWidth: '2px', borderInlineStartColor: 'rgb(228, 0, 43)', borderInlineStartStyle: 'solid', borderInlineStartWidth: '2px', borderLeftColor: 'rgb(228, 0, 43)', borderLeftStyle: 'solid', borderLeftWidth: '2px', borderRightColor: 'rgb(228, 0, 43)', borderRightStyle: 'solid', borderRightWidth: '2px', borderStartEndRadius: '3px', borderStartStartRadius: '3px', borderTopColor: 'rgb(228, 0, 43)', borderTopLeftRadius: '3px', borderTopRightRadius: '3px', borderTopStyle: 'solid', borderTopWidth: '2px', boxSizing: 'content-box', caretColor: 'rgb(228, 0, 43)', color: 'rgb(228, 0, 43)', columnRuleColor: 'rgb(228, 0, 43)', cursor: 'pointer', display: 'block', fontFamily: 'National2, National2Condensed, monospace, sans-serif', fontSize: '16px', fontWeight: 700, inlineSize: '270.398px', marginLeft: 0, marginRight: 0, outlineColor: 'rgb(228, 0, 43)', paddingBlockEnd: '10px', paddingBlockStart: '10px', paddingBottom: '10px', paddingTop: '10px', textAlign: 'center', textDecoration: 'none', textDecorationColor: 'rgb(228, 0, 43)', textEmphasisColor: 'rgb(228, 0, 43)', WebkitTextFillColor: 'rgb(228, 0, 43)', WebkitTextStrokeColor: 'rgb(228, 0, 43)'}} className = {"requestLink"} id = {"RFA"} href = {"https://portalrfa.yum.com/yumRFA/RequestForAccess.jsp"} >
                            <span style={{borderBlockEndColor: 'rgb(228, 0, 43)', borderBlockStartColor: 'rgb(228, 0, 43)', borderBottomColor: 'rgb(228, 0, 43)', borderInlineEndColor: 'rgb(228, 0, 43)', borderInlineStartColor: 'rgb(228, 0, 43)', borderLeftColor: 'rgb(228, 0, 43)', borderRightColor: 'rgb(228, 0, 43)', borderTopColor: 'rgb(228, 0, 43)', boxSizing: 'content-box', caretColor: 'rgb(228, 0, 43)', color: 'rgb(228, 0, 43)', columnRuleColor: 'rgb(228, 0, 43)', cursor: 'pointer', fontFamily: 'National2, National2Condensed, monospace, sans-serif', fontSize: '16px', fontWeight: 700, marginLeft: 0, marginRight: 0, outlineColor: 'rgb(228, 0, 43)', textAlign: 'center', textDecoration: 'none solid rgb(228, 0, 43)', textDecorationColor: 'rgb(228, 0, 43)', textEmphasisColor: 'rgb(228, 0, 43)', WebkitTextFillColor: 'rgb(228, 0, 43)', WebkitTextStrokeColor: 'rgb(228, 0, 43)'}} >Request access</span>
                        </a>
                    </div>
                </div>
            </div>
            <div style={{blockSize: '41px', borderBlockEndColor: 'rgb(228, 0, 43)', borderBlockStartColor: 'rgb(228, 0, 43)', borderBottomColor: 'rgb(228, 0, 43)', borderInlineEndColor: 'rgb(228, 0, 43)', borderInlineStartColor: 'rgb(228, 0, 43)', borderLeftColor: 'rgb(228, 0, 43)', borderRightColor: 'rgb(228, 0, 43)', borderTopColor: 'rgb(228, 0, 43)', boxSizing: 'content-box', caretColor: 'rgb(228, 0, 43)', color: 'rgb(228, 0, 43)', columnRuleColor: 'rgb(228, 0, 43)', fontFamily: 'National2, National2Condensed, monospace, sans-serif', fontSize: '12px', inlineSize: '950px', marginBlockStart: '10px', marginLeft: 0, marginRight: 0, marginTop: '10px', outlineColor: 'rgb(228, 0, 43)', paddingBlockEnd: '10px', paddingBlockStart: '10px', paddingBottom: '10px', paddingTop: '10px', textAlign: 'center', textDecoration: 'none solid rgb(228, 0, 43)', textDecorationColor: 'rgb(228, 0, 43)', textEmphasisColor: 'rgb(228, 0, 43)', WebkitTextFillColor: 'rgb(228, 0, 43)', WebkitTextStrokeColor: 'rgb(228, 0, 43)'}} id = {"brand_error"} className = {"error"} >
                <div style={{blockSize: '15.5px', borderBlockEndColor: 'rgb(228, 0, 43)', borderBlockStartColor: 'rgb(228, 0, 43)', borderBottomColor: 'rgb(228, 0, 43)', borderInlineEndColor: 'rgb(228, 0, 43)', borderInlineStartColor: 'rgb(228, 0, 43)', borderLeftColor: 'rgb(228, 0, 43)', borderRightColor: 'rgb(228, 0, 43)', borderTopColor: 'rgb(228, 0, 43)', boxSizing: 'content-box', caretColor: 'rgb(228, 0, 43)', color: 'rgb(228, 0, 43)', columnRuleColor: 'rgb(228, 0, 43)', fontFamily: 'National2, National2Condensed, monospace, sans-serif', fontSize: '12px', inlineSize: '950px', marginLeft: 0, marginRight: 0, outlineColor: 'rgb(228, 0, 43)', textAlign: 'center', textDecoration: 'none solid rgb(228, 0, 43)', textDecorationColor: 'rgb(228, 0, 43)', textEmphasisColor: 'rgb(228, 0, 43)', WebkitTextFillColor: 'rgb(228, 0, 43)', WebkitTextStrokeColor: 'rgb(228, 0, 43)'}} > MERIT restaurant and Franchise employees call the 1-800-435-7532</div>
                <div style={{blockSize: '15.5px', borderBlockEndColor: 'rgb(228, 0, 43)', borderBlockStartColor: 'rgb(228, 0, 43)', borderBottomColor: 'rgb(228, 0, 43)', borderInlineEndColor: 'rgb(228, 0, 43)', borderInlineStartColor: 'rgb(228, 0, 43)', borderLeftColor: 'rgb(228, 0, 43)', borderRightColor: 'rgb(228, 0, 43)', borderTopColor: 'rgb(228, 0, 43)', boxSizing: 'content-box', caretColor: 'rgb(228, 0, 43)', color: 'rgb(228, 0, 43)', columnRuleColor: 'rgb(228, 0, 43)', fontFamily: 'National2, National2Condensed, monospace, sans-serif', fontSize: '12px', inlineSize: '950px', marginBlockStart: '10px', marginLeft: 0, marginRight: 0, marginTop: '10px', outlineColor: 'rgb(228, 0, 43)', textAlign: 'center', textDecoration: 'none solid rgb(228, 0, 43)', textDecorationColor: 'rgb(228, 0, 43)', textEmphasisColor: 'rgb(228, 0, 43)', WebkitTextFillColor: 'rgb(228, 0, 43)', WebkitTextStrokeColor: 'rgb(228, 0, 43)'}} >KFC Corporate employees call 1-877-498-6986</div>
            </div>
            <div style={{blockSize: '124px', boxSizing: 'content-box', fontFamily: 'National2, National2Condensed, monospace, sans-serif', fontSize: '20px', inlineSize: '890px', marginLeft: 0, marginRight: 0, paddingBlockEnd: '30px', paddingBlockStart: '30px', paddingBottom: '30px', paddingInlineEnd: '30px', paddingInlineStart: '30px', paddingLeft: '30px', paddingRight: '30px', paddingTop: '30px'}} className = {"legal"} >
                <p style={{blockSize: '124px', borderBlockEndColor: 'rgb(181, 181, 181)', borderBlockStartColor: 'rgb(181, 181, 181)', borderBottomColor: 'rgb(181, 181, 181)', borderInlineEndColor: 'rgb(181, 181, 181)', borderInlineStartColor: 'rgb(181, 181, 181)', borderLeftColor: 'rgb(181, 181, 181)', borderRightColor: 'rgb(181, 181, 181)', borderTopColor: 'rgb(181, 181, 181)', boxSizing: 'content-box', caretColor: 'rgb(181, 181, 181)', color: 'rgb(181, 181, 181)', columnRuleColor: 'rgb(181, 181, 181)', fontFamily: 'National2, National2Condensed, monospace, sans-serif', fontSize: '12px', inlineSize: '890px', marginBlockEnd: '0px', marginBlockStart: '0px', marginBottom: '0px', marginLeft: 0, marginRight: 0, marginTop: '0px', outlineColor: 'rgb(181, 181, 181)', textDecoration: 'none solid rgb(181, 181, 181)', textDecorationColor: 'rgb(181, 181, 181)', textEmphasisColor: 'rgb(181, 181, 181)', WebkitTextFillColor: 'rgb(181, 181, 181)', WebkitTextStrokeColor: 'rgb(181, 181, 181)'}} id = {"legalKFC"} >By accessing this website you agree to the following (do not access the website if
                    you do not agree): This is a private computer facility of Yum Brands Restaurant Systems Group,
                    Inc ("Yum"). You may not access this website or its content unless you are authorized in writing
                    or by electronic agreement by Yum to do so, and unless you also are a current employee or
                    contractor of (i) Yum, (ii) a commonly owned affiliate of Yum (KFC, Pizza Hut, and Taco Bell,
                    each a "Brand"), (iii) a franchisee or licensee of a Brand, or (iv) an approved supplier or
                    agency or consultant of Yum or a Brand. If your employment status has changed, you must notify
                    us (link notify us to following email address - kfctechnologysolutions@yum.com). Use is limited
                    solely to Yum system business purposes, and your use is limited further to only those portions
                    of the website you are specifically authorized in writing to use. Any unauthorized use of this
                    website or content is strictly prohibited and may lead to loss of access, as well as to possible
                    criminal and civil prosecution. This website and all content is the property of (or used by
                    license by) Yum, and may be monitored by Yum (users should have no expectation of privacy). All
                    usage must be in accordance with Yum policies regarding internet and content usage and security
                    as posted by Yum from time to time.
                </p>
            </div>
        </div>
    </div>
</div>
  );
};

// Export the SplashPage component as the default export of this module
export default SplashPage;



